name: glassfy_flutter
description: Flutter plugin for Glassfy, build in-app purchases in minutes and offload the complexity of managing subscriptions and on-time purchases. Supports iOS, macOS and Android.
version: 1.3.5
homepage: https://github.com/glassfy/glassfy-flutter

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.7.0
  json_serializable: ^6.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: io.glassfy.glassfy_flutter
        pluginClass: GlassfyFlutterPlugin
      ios:
        pluginClass: GlassfyFlutterPlugin
      macos: 
        pluginClass: GlassfyFlutterPlugin
        
